--- #YAML:1.0
name:                   WWW-Scraper-ISBN-Pearson_Driver
version:                0.16
abstract:               Search driver for the Pearson Education online book catalog
author:
  - Barbie <barbie@cpan.org>

license:                perl
distribution_type:      module
installdirs:            site

requires:
  Test::More:                   0.45
  WWW::Mechanize:               1.60
  WWW::Scraper::ISBN:           0.25
  WWW::Scraper::ISBN::Driver:   0.18
recommends:
  Test::More:                   0.70
  Test::Pod:                    1.00
  Test::Pod::Coverage:          0.08
  Test::CPAN::Meta:             0.13
  Test::JSON::Meta:             0.08
build_requires:
  Test::More:                   0.45

provides:
  WWW::Scraper::ISBN::Pearson_Driver:
    file:     lib/WWW/Scraper/ISBN/Pearson_Driver.pm
    version:  0.16
no_index:
  directory:
    - t
    - examples

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
