# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Scraper-ISBN-Pearson_Driver
version:      0.05
version_from: lib/WWW/Scraper/ISBN/Pearson_Driver.pm
installdirs:  site
requires:
    Template::Extract:             0
    WWW::Mechanize:                0
    WWW::Scraper::ISBN:            0.23
    WWW::Scraper::ISBN::Driver:    0.16

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
